// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/app_api.dart';
import 'api/channel_api.dart';
import 'api/chat_api.dart';
import 'api/contacts_api.dart';
import 'api/conversation_id_util.dart';
import 'api/download_api.dart';
import 'api/emotion_api.dart';
import 'api/group_api.dart';
import 'api/login_api.dart';
import 'api/model/chat.dart';
import 'api/model/client_info.dart';
import 'api/model/contacts.dart';
import 'api/model/conversation.dart';
import 'api/model/ffi_channel_model.dart';
import 'api/model/ffi_download.dart';
import 'api/model/ffi_emotion_model.dart';
import 'api/model/ffi_init_params.dart';
import 'api/model/ffi_message_common.dart';
import 'api/model/ffi_message_content.dart';
import 'api/model/ffi_message_content_audio.dart';
import 'api/model/ffi_message_content_dice.dart';
import 'api/model/ffi_message_content_dynamic_image.dart';
import 'api/model/ffi_message_content_file.dart';
import 'api/model/ffi_message_content_game.dart';
import 'api/model/ffi_message_content_group_event.dart';
import 'api/model/ffi_message_content_html.dart';
import 'api/model/ffi_message_content_html2.dart';
import 'api/model/ffi_message_content_image.dart';
import 'api/model/ffi_message_content_location.dart';
import 'api/model/ffi_message_content_medias_caption.dart';
import 'api/model/ffi_message_content_name_card.dart';
import 'api/model/ffi_message_content_notice.dart';
import 'api/model/ffi_message_content_redpacket.dart';
import 'api/model/ffi_message_content_system.dart';
import 'api/model/ffi_message_content_text.dart';
import 'api/model/ffi_message_content_transfer.dart';
import 'api/model/ffi_message_content_unknown.dart';
import 'api/model/ffi_message_content_video.dart';
import 'api/model/ffi_message_model.dart';
import 'api/model/ffi_message_user.dart';
import 'api/model/group.dart';
import 'api/model/login.dart';
import 'api/model/user.dart';
import 'api/user_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'pb/common.dart';
import 'pb/contacts.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcFfiMessageContentTraitPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArcFfiMessageContentTrait
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  ArcFfiMessageContentTrait
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<FfiUser> dco_decode_StreamSink_ffi_user_Sse(dynamic raw);

  @protected
  RustStreamSink<Rust2ClientMessagePayload>
  dco_decode_StreamSink_rust_2_client_message_payload_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  FfiMessageContentTrait dco_decode_TraitDef_FfiMessageContentTrait(
    dynamic raw,
  );

  @protected
  AccountType dco_decode_account_type(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ContactsDetailBase dco_decode_box_autoadd_contacts_detail_base(dynamic raw);

  @protected
  ContactsParam dco_decode_box_autoadd_contacts_param(dynamic raw);

  @protected
  FfiAnmatedMessageContent dco_decode_box_autoadd_ffi_anmated_message_content(
    dynamic raw,
  );

  @protected
  FfiAudioMessageContent dco_decode_box_autoadd_ffi_audio_message_content(
    dynamic raw,
  );

  @protected
  FfiChannelModel dco_decode_box_autoadd_ffi_channel_model(dynamic raw);

  @protected
  FfiChatTransferMessageContent
  dco_decode_box_autoadd_ffi_chat_transfer_message_content(dynamic raw);

  @protected
  FfiChatType dco_decode_box_autoadd_ffi_chat_type(dynamic raw);

  @protected
  FfiClientInfo dco_decode_box_autoadd_ffi_client_info(dynamic raw);

  @protected
  FfiConversation dco_decode_box_autoadd_ffi_conversation(dynamic raw);

  @protected
  FfiDiceMessageContent dco_decode_box_autoadd_ffi_dice_message_content(
    dynamic raw,
  );

  @protected
  FfiDynamicImageMessageContent
  dco_decode_box_autoadd_ffi_dynamic_image_message_content(dynamic raw);

  @protected
  FfiFileMessageContent dco_decode_box_autoadd_ffi_file_message_content(
    dynamic raw,
  );

  @protected
  FfiGroupBase dco_decode_box_autoadd_ffi_group_base(dynamic raw);

  @protected
  FfiGroupEventMessageContent
  dco_decode_box_autoadd_ffi_group_event_message_content(dynamic raw);

  @protected
  FfiHtml2MessageContent dco_decode_box_autoadd_ffi_html_2_message_content(
    dynamic raw,
  );

  @protected
  FfiHtmlMessageContent dco_decode_box_autoadd_ffi_html_message_content(
    dynamic raw,
  );

  @protected
  FfiImageMessageContent dco_decode_box_autoadd_ffi_image_message_content(
    dynamic raw,
  );

  @protected
  FfiInitParams dco_decode_box_autoadd_ffi_init_params(dynamic raw);

  @protected
  FfiLocationMessageContent dco_decode_box_autoadd_ffi_location_message_content(
    dynamic raw,
  );

  @protected
  FfiMediasCaptionMessageContent
  dco_decode_box_autoadd_ffi_medias_caption_message_content(dynamic raw);

  @protected
  FfiMessageMetaData dco_decode_box_autoadd_ffi_message_meta_data(dynamic raw);

  @protected
  FfiMessageModel dco_decode_box_autoadd_ffi_message_model(dynamic raw);

  @protected
  FfiMsgContent dco_decode_box_autoadd_ffi_msg_content(dynamic raw);

  @protected
  FfiNameCardMessageContent
  dco_decode_box_autoadd_ffi_name_card_message_content(dynamic raw);

  @protected
  FfiNoticeMessageContent dco_decode_box_autoadd_ffi_notice_message_content(
    dynamic raw,
  );

  @protected
  FfiRedPacketMessageContent
  dco_decode_box_autoadd_ffi_red_packet_message_content(dynamic raw);

  @protected
  FfiReferenceObj dco_decode_box_autoadd_ffi_reference_obj(dynamic raw);

  @protected
  FfiSystemMessageContent dco_decode_box_autoadd_ffi_system_message_content(
    dynamic raw,
  );

  @protected
  FfiTextMessageContent dco_decode_box_autoadd_ffi_text_message_content(
    dynamic raw,
  );

  @protected
  FfiUnknownMessageContent dco_decode_box_autoadd_ffi_unknown_message_content(
    dynamic raw,
  );

  @protected
  FfiUrlInfo dco_decode_box_autoadd_ffi_url_info(dynamic raw);

  @protected
  FfiUser dco_decode_box_autoadd_ffi_user(dynamic raw);

  @protected
  FfiUserBase dco_decode_box_autoadd_ffi_user_base(dynamic raw);

  @protected
  FfiVideoMessageContent dco_decode_box_autoadd_ffi_video_message_content(
    dynamic raw,
  );

  @protected
  FriendRelation dco_decode_box_autoadd_friend_relation(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  UserBase dco_decode_box_autoadd_user_base(dynamic raw);

  @protected
  UserOnOrOffLine dco_decode_box_autoadd_user_on_or_off_line(dynamic raw);

  @protected
  ContactOrderType dco_decode_contact_order_type(dynamic raw);

  @protected
  ContactsDetailBase dco_decode_contacts_detail_base(dynamic raw);

  @protected
  ContactsOperator dco_decode_contacts_operator(dynamic raw);

  @protected
  ContactsParam dco_decode_contacts_param(dynamic raw);

  @protected
  DownloadProgressInfo dco_decode_download_progress_info(dynamic raw);

  @protected
  DownloadResult dco_decode_download_result(dynamic raw);

  @protected
  DownloadTask dco_decode_download_task(dynamic raw);

  @protected
  DownloadTaskEnhanced dco_decode_download_task_enhanced(dynamic raw);

  @protected
  DownloadType dco_decode_download_type(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FfiAnimatedGameConfig dco_decode_ffi_animated_game_config(dynamic raw);

  @protected
  FfiAnmatedMessageContent dco_decode_ffi_anmated_message_content(dynamic raw);

  @protected
  FfiAudioMessageContent dco_decode_ffi_audio_message_content(dynamic raw);

  @protected
  FfiChannelModel dco_decode_ffi_channel_model(dynamic raw);

  @protected
  FfiChatTransferMessageContent dco_decode_ffi_chat_transfer_message_content(
    dynamic raw,
  );

  @protected
  FfiChatType dco_decode_ffi_chat_type(dynamic raw);

  @protected
  FfiClientInfo dco_decode_ffi_client_info(dynamic raw);

  @protected
  FfiCommonMessageModel dco_decode_ffi_common_message_model(dynamic raw);

  @protected
  FfiContactDetail dco_decode_ffi_contact_detail(dynamic raw);

  @protected
  FfiConversation dco_decode_ffi_conversation(dynamic raw);

  @protected
  FfiDiceMessageContent dco_decode_ffi_dice_message_content(dynamic raw);

  @protected
  FfiDynamicImageMessageContent dco_decode_ffi_dynamic_image_message_content(
    dynamic raw,
  );

  @protected
  FfiEmoticonBase dco_decode_ffi_emoticon_base(dynamic raw);

  @protected
  FfiEmoticonListResult dco_decode_ffi_emoticon_list_result(dynamic raw);

  @protected
  FfiEmotionInfoType dco_decode_ffi_emotion_info_type(dynamic raw);

  @protected
  FfiFileMessageContent dco_decode_ffi_file_message_content(dynamic raw);

  @protected
  FfiGetEmoticonResponse dco_decode_ffi_get_emoticon_response(dynamic raw);

  @protected
  FfiGroupBase dco_decode_ffi_group_base(dynamic raw);

  @protected
  FfiGroupDetailResponse dco_decode_ffi_group_detail_response(dynamic raw);

  @protected
  FfiGroupEventMessageContent dco_decode_ffi_group_event_message_content(
    dynamic raw,
  );

  @protected
  FfiHtml2MessageContent dco_decode_ffi_html_2_message_content(dynamic raw);

  @protected
  FfiHtmlMessageContent dco_decode_ffi_html_message_content(dynamic raw);

  @protected
  FfiImageMessageContent dco_decode_ffi_image_message_content(dynamic raw);

  @protected
  FfiInitParams dco_decode_ffi_init_params(dynamic raw);

  @protected
  FfiLocationMessageContent dco_decode_ffi_location_message_content(
    dynamic raw,
  );

  @protected
  FfiLoginResponse dco_decode_ffi_login_response(dynamic raw);

  @protected
  FfiMediasCaptionMessageContent dco_decode_ffi_medias_caption_message_content(
    dynamic raw,
  );

  @protected
  FfiMessageMetaData dco_decode_ffi_message_meta_data(dynamic raw);

  @protected
  FfiMessageModel dco_decode_ffi_message_model(dynamic raw);

  @protected
  FfiMessageUser dco_decode_ffi_message_user(dynamic raw);

  @protected
  FfiMsgContent dco_decode_ffi_msg_content(dynamic raw);

  @protected
  FfiMsgStatus dco_decode_ffi_msg_status(dynamic raw);

  @protected
  FfiMsgType dco_decode_ffi_msg_type(dynamic raw);

  @protected
  FfiNameCardMessageContent dco_decode_ffi_name_card_message_content(
    dynamic raw,
  );

  @protected
  FfiNoticeMessageContent dco_decode_ffi_notice_message_content(dynamic raw);

  @protected
  FfiPushNotificationType dco_decode_ffi_push_notification_type(dynamic raw);

  @protected
  FfiRedPacketMessageContent dco_decode_ffi_red_packet_message_content(
    dynamic raw,
  );

  @protected
  FfiReferenceObj dco_decode_ffi_reference_obj(dynamic raw);

  @protected
  FfiRegResponse dco_decode_ffi_reg_response(dynamic raw);

  @protected
  FfiSystemMessageContent dco_decode_ffi_system_message_content(dynamic raw);

  @protected
  FfiTextMessageContent dco_decode_ffi_text_message_content(dynamic raw);

  @protected
  FfiUnknownMessageContent dco_decode_ffi_unknown_message_content(dynamic raw);

  @protected
  FfiUrlInfo dco_decode_ffi_url_info(dynamic raw);

  @protected
  FfiUser dco_decode_ffi_user(dynamic raw);

  @protected
  FfiUserBase dco_decode_ffi_user_base(dynamic raw);

  @protected
  FfiVideoMessageContent dco_decode_ffi_video_message_content(dynamic raw);

  @protected
  FileOverwritePolicy dco_decode_file_overwrite_policy(dynamic raw);

  @protected
  FriendRelation dco_decode_friend_relation(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<DownloadResult> dco_decode_list_download_result(dynamic raw);

  @protected
  List<DownloadTask> dco_decode_list_download_task(dynamic raw);

  @protected
  List<DownloadTaskEnhanced> dco_decode_list_download_task_enhanced(
    dynamic raw,
  );

  @protected
  List<FfiAnimatedGameConfig> dco_decode_list_ffi_animated_game_config(
    dynamic raw,
  );

  @protected
  List<FfiChannelModel> dco_decode_list_ffi_channel_model(dynamic raw);

  @protected
  List<FfiContactDetail> dco_decode_list_ffi_contact_detail(dynamic raw);

  @protected
  List<FfiConversation> dco_decode_list_ffi_conversation(dynamic raw);

  @protected
  List<FfiEmoticonBase> dco_decode_list_ffi_emoticon_base(dynamic raw);

  @protected
  List<FfiGroupBase> dco_decode_list_ffi_group_base(dynamic raw);

  @protected
  List<FfiMessageModel> dco_decode_list_ffi_message_model(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(FfiChatType, PlatformInt64)> dco_decode_list_record_ffi_chat_type_i_64(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  MessageError dco_decode_message_error(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  FfiChannelModel? dco_decode_opt_box_autoadd_ffi_channel_model(dynamic raw);

  @protected
  FfiChatType? dco_decode_opt_box_autoadd_ffi_chat_type(dynamic raw);

  @protected
  FfiConversation? dco_decode_opt_box_autoadd_ffi_conversation(dynamic raw);

  @protected
  FfiGroupBase? dco_decode_opt_box_autoadd_ffi_group_base(dynamic raw);

  @protected
  FfiReferenceObj? dco_decode_opt_box_autoadd_ffi_reference_obj(dynamic raw);

  @protected
  FfiUrlInfo? dco_decode_opt_box_autoadd_ffi_url_info(dynamic raw);

  @protected
  FfiUserBase? dco_decode_opt_box_autoadd_ffi_user_base(dynamic raw);

  @protected
  FriendRelation? dco_decode_opt_box_autoadd_friend_relation(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  UserBase? dco_decode_opt_box_autoadd_user_base(dynamic raw);

  @protected
  UserOnOrOffLine? dco_decode_opt_box_autoadd_user_on_or_off_line(dynamic raw);

  @protected
  (FfiChatType, PlatformInt64) dco_decode_record_ffi_chat_type_i_64(
    dynamic raw,
  );

  @protected
  (String, FfiReferenceObj?)
  dco_decode_record_string_opt_box_autoadd_ffi_reference_obj(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  Rust2ClientMessagePayload dco_decode_rust_2_client_message_payload(
    dynamic raw,
  );

  @protected
  Rust2ClientMessageType dco_decode_rust_2_client_message_type(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserBase dco_decode_user_base(dynamic raw);

  @protected
  UserOnOrOffLine dco_decode_user_on_or_off_line(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArcFfiMessageContentTrait
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  ArcFfiMessageContentTrait
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FfiUser> sse_decode_StreamSink_ffi_user_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Rust2ClientMessagePayload>
  sse_decode_StreamSink_rust_2_client_message_payload_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountType sse_decode_account_type(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ContactsDetailBase sse_decode_box_autoadd_contacts_detail_base(
    SseDeserializer deserializer,
  );

  @protected
  ContactsParam sse_decode_box_autoadd_contacts_param(
    SseDeserializer deserializer,
  );

  @protected
  FfiAnmatedMessageContent sse_decode_box_autoadd_ffi_anmated_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiAudioMessageContent sse_decode_box_autoadd_ffi_audio_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiChannelModel sse_decode_box_autoadd_ffi_channel_model(
    SseDeserializer deserializer,
  );

  @protected
  FfiChatTransferMessageContent
  sse_decode_box_autoadd_ffi_chat_transfer_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiChatType sse_decode_box_autoadd_ffi_chat_type(
    SseDeserializer deserializer,
  );

  @protected
  FfiClientInfo sse_decode_box_autoadd_ffi_client_info(
    SseDeserializer deserializer,
  );

  @protected
  FfiConversation sse_decode_box_autoadd_ffi_conversation(
    SseDeserializer deserializer,
  );

  @protected
  FfiDiceMessageContent sse_decode_box_autoadd_ffi_dice_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiDynamicImageMessageContent
  sse_decode_box_autoadd_ffi_dynamic_image_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiFileMessageContent sse_decode_box_autoadd_ffi_file_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiGroupBase sse_decode_box_autoadd_ffi_group_base(
    SseDeserializer deserializer,
  );

  @protected
  FfiGroupEventMessageContent
  sse_decode_box_autoadd_ffi_group_event_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiHtml2MessageContent sse_decode_box_autoadd_ffi_html_2_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiHtmlMessageContent sse_decode_box_autoadd_ffi_html_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiImageMessageContent sse_decode_box_autoadd_ffi_image_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiInitParams sse_decode_box_autoadd_ffi_init_params(
    SseDeserializer deserializer,
  );

  @protected
  FfiLocationMessageContent sse_decode_box_autoadd_ffi_location_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiMediasCaptionMessageContent
  sse_decode_box_autoadd_ffi_medias_caption_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiMessageMetaData sse_decode_box_autoadd_ffi_message_meta_data(
    SseDeserializer deserializer,
  );

  @protected
  FfiMessageModel sse_decode_box_autoadd_ffi_message_model(
    SseDeserializer deserializer,
  );

  @protected
  FfiMsgContent sse_decode_box_autoadd_ffi_msg_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiNameCardMessageContent
  sse_decode_box_autoadd_ffi_name_card_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiNoticeMessageContent sse_decode_box_autoadd_ffi_notice_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiRedPacketMessageContent
  sse_decode_box_autoadd_ffi_red_packet_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiReferenceObj sse_decode_box_autoadd_ffi_reference_obj(
    SseDeserializer deserializer,
  );

  @protected
  FfiSystemMessageContent sse_decode_box_autoadd_ffi_system_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiTextMessageContent sse_decode_box_autoadd_ffi_text_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiUnknownMessageContent sse_decode_box_autoadd_ffi_unknown_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiUrlInfo sse_decode_box_autoadd_ffi_url_info(SseDeserializer deserializer);

  @protected
  FfiUser sse_decode_box_autoadd_ffi_user(SseDeserializer deserializer);

  @protected
  FfiUserBase sse_decode_box_autoadd_ffi_user_base(
    SseDeserializer deserializer,
  );

  @protected
  FfiVideoMessageContent sse_decode_box_autoadd_ffi_video_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FriendRelation sse_decode_box_autoadd_friend_relation(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  UserBase sse_decode_box_autoadd_user_base(SseDeserializer deserializer);

  @protected
  UserOnOrOffLine sse_decode_box_autoadd_user_on_or_off_line(
    SseDeserializer deserializer,
  );

  @protected
  ContactOrderType sse_decode_contact_order_type(SseDeserializer deserializer);

  @protected
  ContactsDetailBase sse_decode_contacts_detail_base(
    SseDeserializer deserializer,
  );

  @protected
  ContactsOperator sse_decode_contacts_operator(SseDeserializer deserializer);

  @protected
  ContactsParam sse_decode_contacts_param(SseDeserializer deserializer);

  @protected
  DownloadProgressInfo sse_decode_download_progress_info(
    SseDeserializer deserializer,
  );

  @protected
  DownloadResult sse_decode_download_result(SseDeserializer deserializer);

  @protected
  DownloadTask sse_decode_download_task(SseDeserializer deserializer);

  @protected
  DownloadTaskEnhanced sse_decode_download_task_enhanced(
    SseDeserializer deserializer,
  );

  @protected
  DownloadType sse_decode_download_type(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FfiAnimatedGameConfig sse_decode_ffi_animated_game_config(
    SseDeserializer deserializer,
  );

  @protected
  FfiAnmatedMessageContent sse_decode_ffi_anmated_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiAudioMessageContent sse_decode_ffi_audio_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiChannelModel sse_decode_ffi_channel_model(SseDeserializer deserializer);

  @protected
  FfiChatTransferMessageContent sse_decode_ffi_chat_transfer_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiChatType sse_decode_ffi_chat_type(SseDeserializer deserializer);

  @protected
  FfiClientInfo sse_decode_ffi_client_info(SseDeserializer deserializer);

  @protected
  FfiCommonMessageModel sse_decode_ffi_common_message_model(
    SseDeserializer deserializer,
  );

  @protected
  FfiContactDetail sse_decode_ffi_contact_detail(SseDeserializer deserializer);

  @protected
  FfiConversation sse_decode_ffi_conversation(SseDeserializer deserializer);

  @protected
  FfiDiceMessageContent sse_decode_ffi_dice_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiDynamicImageMessageContent sse_decode_ffi_dynamic_image_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiEmoticonBase sse_decode_ffi_emoticon_base(SseDeserializer deserializer);

  @protected
  FfiEmoticonListResult sse_decode_ffi_emoticon_list_result(
    SseDeserializer deserializer,
  );

  @protected
  FfiEmotionInfoType sse_decode_ffi_emotion_info_type(
    SseDeserializer deserializer,
  );

  @protected
  FfiFileMessageContent sse_decode_ffi_file_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiGetEmoticonResponse sse_decode_ffi_get_emoticon_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiGroupBase sse_decode_ffi_group_base(SseDeserializer deserializer);

  @protected
  FfiGroupDetailResponse sse_decode_ffi_group_detail_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiGroupEventMessageContent sse_decode_ffi_group_event_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiHtml2MessageContent sse_decode_ffi_html_2_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiHtmlMessageContent sse_decode_ffi_html_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiImageMessageContent sse_decode_ffi_image_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiInitParams sse_decode_ffi_init_params(SseDeserializer deserializer);

  @protected
  FfiLocationMessageContent sse_decode_ffi_location_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiLoginResponse sse_decode_ffi_login_response(SseDeserializer deserializer);

  @protected
  FfiMediasCaptionMessageContent sse_decode_ffi_medias_caption_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiMessageMetaData sse_decode_ffi_message_meta_data(
    SseDeserializer deserializer,
  );

  @protected
  FfiMessageModel sse_decode_ffi_message_model(SseDeserializer deserializer);

  @protected
  FfiMessageUser sse_decode_ffi_message_user(SseDeserializer deserializer);

  @protected
  FfiMsgContent sse_decode_ffi_msg_content(SseDeserializer deserializer);

  @protected
  FfiMsgStatus sse_decode_ffi_msg_status(SseDeserializer deserializer);

  @protected
  FfiMsgType sse_decode_ffi_msg_type(SseDeserializer deserializer);

  @protected
  FfiNameCardMessageContent sse_decode_ffi_name_card_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiNoticeMessageContent sse_decode_ffi_notice_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiPushNotificationType sse_decode_ffi_push_notification_type(
    SseDeserializer deserializer,
  );

  @protected
  FfiRedPacketMessageContent sse_decode_ffi_red_packet_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiReferenceObj sse_decode_ffi_reference_obj(SseDeserializer deserializer);

  @protected
  FfiRegResponse sse_decode_ffi_reg_response(SseDeserializer deserializer);

  @protected
  FfiSystemMessageContent sse_decode_ffi_system_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiTextMessageContent sse_decode_ffi_text_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiUnknownMessageContent sse_decode_ffi_unknown_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FfiUrlInfo sse_decode_ffi_url_info(SseDeserializer deserializer);

  @protected
  FfiUser sse_decode_ffi_user(SseDeserializer deserializer);

  @protected
  FfiUserBase sse_decode_ffi_user_base(SseDeserializer deserializer);

  @protected
  FfiVideoMessageContent sse_decode_ffi_video_message_content(
    SseDeserializer deserializer,
  );

  @protected
  FileOverwritePolicy sse_decode_file_overwrite_policy(
    SseDeserializer deserializer,
  );

  @protected
  FriendRelation sse_decode_friend_relation(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<DownloadResult> sse_decode_list_download_result(
    SseDeserializer deserializer,
  );

  @protected
  List<DownloadTask> sse_decode_list_download_task(
    SseDeserializer deserializer,
  );

  @protected
  List<DownloadTaskEnhanced> sse_decode_list_download_task_enhanced(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiAnimatedGameConfig> sse_decode_list_ffi_animated_game_config(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiChannelModel> sse_decode_list_ffi_channel_model(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiContactDetail> sse_decode_list_ffi_contact_detail(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiConversation> sse_decode_list_ffi_conversation(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiEmoticonBase> sse_decode_list_ffi_emoticon_base(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiGroupBase> sse_decode_list_ffi_group_base(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiMessageModel> sse_decode_list_ffi_message_model(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(FfiChatType, PlatformInt64)> sse_decode_list_record_ffi_chat_type_i_64(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  MessageError sse_decode_message_error(SseDeserializer deserializer);

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  FfiChannelModel? sse_decode_opt_box_autoadd_ffi_channel_model(
    SseDeserializer deserializer,
  );

  @protected
  FfiChatType? sse_decode_opt_box_autoadd_ffi_chat_type(
    SseDeserializer deserializer,
  );

  @protected
  FfiConversation? sse_decode_opt_box_autoadd_ffi_conversation(
    SseDeserializer deserializer,
  );

  @protected
  FfiGroupBase? sse_decode_opt_box_autoadd_ffi_group_base(
    SseDeserializer deserializer,
  );

  @protected
  FfiReferenceObj? sse_decode_opt_box_autoadd_ffi_reference_obj(
    SseDeserializer deserializer,
  );

  @protected
  FfiUrlInfo? sse_decode_opt_box_autoadd_ffi_url_info(
    SseDeserializer deserializer,
  );

  @protected
  FfiUserBase? sse_decode_opt_box_autoadd_ffi_user_base(
    SseDeserializer deserializer,
  );

  @protected
  FriendRelation? sse_decode_opt_box_autoadd_friend_relation(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  UserBase? sse_decode_opt_box_autoadd_user_base(SseDeserializer deserializer);

  @protected
  UserOnOrOffLine? sse_decode_opt_box_autoadd_user_on_or_off_line(
    SseDeserializer deserializer,
  );

  @protected
  (FfiChatType, PlatformInt64) sse_decode_record_ffi_chat_type_i_64(
    SseDeserializer deserializer,
  );

  @protected
  (String, FfiReferenceObj?)
  sse_decode_record_string_opt_box_autoadd_ffi_reference_obj(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  Rust2ClientMessagePayload sse_decode_rust_2_client_message_payload(
    SseDeserializer deserializer,
  );

  @protected
  Rust2ClientMessageType sse_decode_rust_2_client_message_type(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserBase sse_decode_user_base(SseDeserializer deserializer);

  @protected
  UserOnOrOffLine sse_decode_user_on_or_off_line(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    ArcFfiMessageContentTrait self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    ArcFfiMessageContentTrait self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ffi_user_Sse(
    RustStreamSink<FfiUser> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_rust_2_client_message_payload_Sse(
    RustStreamSink<Rust2ClientMessagePayload> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_type(AccountType self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_contacts_detail_base(
    ContactsDetailBase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_contacts_param(
    ContactsParam self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_anmated_message_content(
    FfiAnmatedMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_audio_message_content(
    FfiAudioMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_channel_model(
    FfiChannelModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_chat_transfer_message_content(
    FfiChatTransferMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_chat_type(
    FfiChatType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_client_info(
    FfiClientInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_conversation(
    FfiConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_dice_message_content(
    FfiDiceMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_dynamic_image_message_content(
    FfiDynamicImageMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_file_message_content(
    FfiFileMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_group_base(
    FfiGroupBase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_group_event_message_content(
    FfiGroupEventMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_html_2_message_content(
    FfiHtml2MessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_html_message_content(
    FfiHtmlMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_image_message_content(
    FfiImageMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_init_params(
    FfiInitParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_location_message_content(
    FfiLocationMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_medias_caption_message_content(
    FfiMediasCaptionMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_message_meta_data(
    FfiMessageMetaData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_message_model(
    FfiMessageModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_msg_content(
    FfiMsgContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_name_card_message_content(
    FfiNameCardMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_notice_message_content(
    FfiNoticeMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_red_packet_message_content(
    FfiRedPacketMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_reference_obj(
    FfiReferenceObj self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_system_message_content(
    FfiSystemMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_text_message_content(
    FfiTextMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_unknown_message_content(
    FfiUnknownMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_url_info(
    FfiUrlInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_user(FfiUser self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_user_base(
    FfiUserBase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_video_message_content(
    FfiVideoMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_friend_relation(
    FriendRelation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_base(
    UserBase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_user_on_or_off_line(
    UserOnOrOffLine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact_order_type(
    ContactOrderType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contacts_detail_base(
    ContactsDetailBase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contacts_operator(
    ContactsOperator self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contacts_param(ContactsParam self, SseSerializer serializer);

  @protected
  void sse_encode_download_progress_info(
    DownloadProgressInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_result(
    DownloadResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_task(DownloadTask self, SseSerializer serializer);

  @protected
  void sse_encode_download_task_enhanced(
    DownloadTaskEnhanced self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_type(DownloadType self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_animated_game_config(
    FfiAnimatedGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_anmated_message_content(
    FfiAnmatedMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_audio_message_content(
    FfiAudioMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_channel_model(
    FfiChannelModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_chat_transfer_message_content(
    FfiChatTransferMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_chat_type(FfiChatType self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_client_info(FfiClientInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_common_message_model(
    FfiCommonMessageModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_contact_detail(
    FfiContactDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_conversation(
    FfiConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_dice_message_content(
    FfiDiceMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_dynamic_image_message_content(
    FfiDynamicImageMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_emoticon_base(
    FfiEmoticonBase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_emoticon_list_result(
    FfiEmoticonListResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_emotion_info_type(
    FfiEmotionInfoType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_file_message_content(
    FfiFileMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_get_emoticon_response(
    FfiGetEmoticonResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_group_base(FfiGroupBase self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_group_detail_response(
    FfiGroupDetailResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_group_event_message_content(
    FfiGroupEventMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_html_2_message_content(
    FfiHtml2MessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_html_message_content(
    FfiHtmlMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_image_message_content(
    FfiImageMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_init_params(FfiInitParams self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_location_message_content(
    FfiLocationMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_login_response(
    FfiLoginResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_medias_caption_message_content(
    FfiMediasCaptionMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_message_meta_data(
    FfiMessageMetaData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_message_model(
    FfiMessageModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_message_user(
    FfiMessageUser self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_msg_content(FfiMsgContent self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_msg_status(FfiMsgStatus self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_msg_type(FfiMsgType self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_name_card_message_content(
    FfiNameCardMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_notice_message_content(
    FfiNoticeMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_push_notification_type(
    FfiPushNotificationType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_red_packet_message_content(
    FfiRedPacketMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_reference_obj(
    FfiReferenceObj self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_reg_response(
    FfiRegResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_system_message_content(
    FfiSystemMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_text_message_content(
    FfiTextMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_unknown_message_content(
    FfiUnknownMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_url_info(FfiUrlInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_user(FfiUser self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_user_base(FfiUserBase self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_video_message_content(
    FfiVideoMessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_overwrite_policy(
    FileOverwritePolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_relation(
    FriendRelation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_download_result(
    List<DownloadResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_download_task(
    List<DownloadTask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_download_task_enhanced(
    List<DownloadTaskEnhanced> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_animated_game_config(
    List<FfiAnimatedGameConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_channel_model(
    List<FfiChannelModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_contact_detail(
    List<FfiContactDetail> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_conversation(
    List<FfiConversation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_emoticon_base(
    List<FfiEmoticonBase> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_group_base(
    List<FfiGroupBase> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_message_model(
    List<FfiMessageModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_ffi_chat_type_i_64(
    List<(FfiChatType, PlatformInt64)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_error(MessageError self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ffi_channel_model(
    FfiChannelModel? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_chat_type(
    FfiChatType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_conversation(
    FfiConversation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_group_base(
    FfiGroupBase? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_reference_obj(
    FfiReferenceObj? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_url_info(
    FfiUrlInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_user_base(
    FfiUserBase? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_friend_relation(
    FriendRelation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_base(
    UserBase? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_user_on_or_off_line(
    UserOnOrOffLine? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_ffi_chat_type_i_64(
    (FfiChatType, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_opt_box_autoadd_ffi_reference_obj(
    (String, FfiReferenceObj?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_2_client_message_payload(
    Rust2ClientMessagePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_2_client_message_type(
    Rust2ClientMessageType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_base(UserBase self, SseSerializer serializer);

  @protected
  void sse_encode_user_on_or_off_line(
    UserOnOrOffLine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFfiMessageContentTrait(
    int ptr,
  );
}
