// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 操作类型
enum ContactsOperator {
  /// 添加联系人
  add,

  /// 删除联系人
  del,

  /// 星标
  star,

  /// 免打扰
  disturb,

  /// 备注
  remark,

  /// 描述
  describe,

  /// 添加黑名单
  addBlack,

  /// 移除黑名单
  delBlack,

  /// 同意请求
  addReq,

  /// 忽略请求
  delReq,

  /// 置顶
  top,

  /// 阅后即焚 add v1.1.0
  readCancel,

  /// 截屏通知 add v1.1.0
  screenshot,

  /// 阅后即焚销毁时间设置 add v1.1.0
  readCancelTime,
}

/// 联系人设置参数体
class ContactsParam {
  /// 联系人ID（必须）
  final PlatformInt64 contactsId;

  /// 备注名
  final String noteName;

  /// 描述
  final String depict;

  /// 星标
  final bool bfStar;

  /// 免打扰
  final bool bfDisturb;

  /// 置顶
  final bool bfTop;

  /// 阅后即焚 add v1.1.0
  final bool bfReadCancel;

  /// 消息销毁时间\[秒\] add v1.1.0
  final int msgCancelTime;

  /// 截屏通知 add v1.1.0
  final bool bfScreenshot;

  const ContactsParam({
    required this.contactsId,
    required this.noteName,
    required this.depict,
    required this.bfStar,
    required this.bfDisturb,
    required this.bfTop,
    required this.bfReadCancel,
    required this.msgCancelTime,
    required this.bfScreenshot,
  });

  @override
  int get hashCode =>
      contactsId.hashCode ^
      noteName.hashCode ^
      depict.hashCode ^
      bfStar.hashCode ^
      bfDisturb.hashCode ^
      bfTop.hashCode ^
      bfReadCancel.hashCode ^
      msgCancelTime.hashCode ^
      bfScreenshot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactsParam &&
          runtimeType == other.runtimeType &&
          contactsId == other.contactsId &&
          noteName == other.noteName &&
          depict == other.depict &&
          bfStar == other.bfStar &&
          bfDisturb == other.bfDisturb &&
          bfTop == other.bfTop &&
          bfReadCancel == other.bfReadCancel &&
          msgCancelTime == other.msgCancelTime &&
          bfScreenshot == other.bfScreenshot;
}
