// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FfiMessageEntityType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// 消息推送类型枚举
enum FfiPushNotificationType {
  /// 不推送任何消息
  none,

  /// 推送会话列表消息（在会话列表页面时）
  conversationList,

  /// 推送会话消息（在会话详情页面时）
  conversation;

  static Future<FfiPushNotificationType> default_() =>
      RustLib.instance.api.crateApiModelChatFfiPushNotificationTypeDefault();
}
