// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/client_info.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Client Info structure for FFI, matching PbClientInfo fields exactly.
@freezed
class FfiClientInfo with _$FfiClientInfo {
  const factory FfiClientInfo({
    required String sessionId,
    required int appVer,
    required int packageCode,
    required int plat,
    required int language,
    required String sysMac,
    required String sysModel,
  }) = _FfiClientInfo;
}
