// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../pb/common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/contacts.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

enum ContactOrderType { presence, natural }

/// 联系人详情的 FFI 模型
@freezed
class FfiContactDetail with _$FfiContactDetail {
  const FfiContactDetail._();
  const factory FfiContactDetail({
    required PlatformInt64 userId,
    required String nickName,
    required String avatar,
    required String depict,
    required bool bfStar,
    required bool bfDisturb,
    required bool bfMyBlack,
    required String letter,
    required bool bfTop,
    required bool bfVerify,
    required String signature,
    required String groupNickName,
    required String phone,
    required bool bfReadCancel,
    required int msgCancelTime,
    required bool bfScreenshot,
    required int commonGroupNum,
    required bool bfReadReceipt,
    required int groupShutupTime,
    required int searchType,
  }) = _FfiContactDetail;
  static Future<FfiContactDetail> from({required ContactsDetailBase detail}) =>
      RustLib.instance.api.crateApiModelContactsFfiContactDetailFrom(
        detail: detail,
      );
}
