// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'ffi_message_common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/conversation.freezed.dart';
part '../../../../generated/src/rust/api/model/conversation.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// 会话列表模型
@freezed
class FfiConversation with _$FfiConversation {
  const factory FfiConversation({
    required String conversationId,
    required FfiChatType chatType,
    required PlatformInt64 targetId,
    required String lastMessage,
    required PlatformInt64 lastMessageTime,
    required FfiMsgType lastMessageType,
    required PlatformInt64 senderUid,
    required String senderName,
    required String name,
    String? avatar,
    required int unreadCount,
    required bool isTopPinned,
    required bool isMuted,
    PlatformInt64? topPinnedAt,
    required bool isArchive,
  }) = _FfiConversation;

  factory FfiConversation.fromJson(Map<String, dynamic> json) =>
      _$FfiConversationFromJson(json);
}
