// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'ffi_message_common.dart';
import 'ffi_message_content.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/ffi_message_content_html2.freezed.dart';
part '../../../../generated/src/rust/api/model/ffi_message_content_html2.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 文本消息内容
@freezed
class FfiHtml2MessageContent with _$FfiHtml2MessageContent {
  const FfiHtml2MessageContent._();
  const factory FfiHtml2MessageContent({required String htmlContent}) =
      _FfiHtml2MessageContent;
  static Future<FfiHtml2MessageContent> default_() =>
      RustLib.instance.api
          .crateApiModelFfiMessageContentHtml2FfiHtml2MessageContentDefault();

  Future<String> ffiToJsonString() => RustLib.instance.api
      .crateApiModelFfiMessageContentHtml2FfiHtml2MessageContentFfiToJsonString(
        that: this,
      );

  Future<Uint8List> ffiToProtoData({
    required String contentObj,
    FfiReferenceObj? ffiRefObj,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentHtml2FfiHtml2MessageContentFfiToProtoData(
        that: this,
        contentObj: contentObj,
        ffiRefObj: ffiRefObj,
      );

  Future<FfiMsgType> getFfiSubMsgType() => RustLib.instance.api
      .crateApiModelFfiMessageContentHtml2FfiHtml2MessageContentGetFfiSubMsgType(
        that: this,
      );

  Future<void> jsonToFfi({required String uniKey, required String jsonStr}) =>
      RustLib.instance.api
          .crateApiModelFfiMessageContentHtml2FfiHtml2MessageContentJsonToFfi(
            that: this,
            uniKey: uniKey,
            jsonStr: jsonStr,
          );

  Future<(String, FfiReferenceObj?)> protoDecodeToJson({
    required List<int> content,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentHtml2FfiHtml2MessageContentProtoDecodeToJson(
        that: this,
        content: content,
      );

  factory FfiHtml2MessageContent.fromJson(Map<String, dynamic> json) =>
      _$FfiHtml2MessageContentFromJson(json);
}
