// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'ffi_message_common.dart';
import 'ffi_message_content.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/ffi_message_content_html.freezed.dart';
part '../../../../generated/src/rust/api/model/ffi_message_content_html.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 文本消息内容
@freezed
class FfiHtmlMessageContent with _$FfiHtmlMessageContent {
  const FfiHtmlMessageContent._();
  const factory FfiHtmlMessageContent({required String htmlContent}) =
      _FfiHtmlMessageContent;
  static Future<FfiHtmlMessageContent> default_() =>
      RustLib.instance.api
          .crateApiModelFfiMessageContentHtmlFfiHtmlMessageContentDefault();

  Future<String> ffiToJsonString() => RustLib.instance.api
      .crateApiModelFfiMessageContentHtmlFfiHtmlMessageContentFfiToJsonString(
        that: this,
      );

  Future<Uint8List> ffiToProtoData({
    required String contentObj,
    FfiReferenceObj? ffiRefObj,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentHtmlFfiHtmlMessageContentFfiToProtoData(
        that: this,
        contentObj: contentObj,
        ffiRefObj: ffiRefObj,
      );

  Future<FfiMsgType> getFfiSubMsgType() => RustLib.instance.api
      .crateApiModelFfiMessageContentHtmlFfiHtmlMessageContentGetFfiSubMsgType(
        that: this,
      );

  Future<void> jsonToFfi({required String uniKey, required String jsonStr}) =>
      RustLib.instance.api
          .crateApiModelFfiMessageContentHtmlFfiHtmlMessageContentJsonToFfi(
            that: this,
            uniKey: uniKey,
            jsonStr: jsonStr,
          );

  Future<(String, FfiReferenceObj?)> protoDecodeToJson({
    required List<int> content,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentHtmlFfiHtmlMessageContentProtoDecodeToJson(
        that: this,
        content: content,
      );

  factory FfiHtmlMessageContent.fromJson(Map<String, dynamic> json) =>
      _$FfiHtmlMessageContentFromJson(json);
}
