// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'ffi_message_common.dart';
import 'ffi_message_content.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/ffi_message_content_dice.freezed.dart';
part '../../../../generated/src/rust/api/model/ffi_message_content_dice.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 文本消息内容
@freezed
class FfiDiceMessageContent with _$FfiDiceMessageContent {
  const FfiDiceMessageContent._();
  const factory FfiDiceMessageContent({
    required PlatformInt64 setImageId,
    required int imageSize,
    required int currentImage,
  }) = _FfiDiceMessageContent;
  static Future<FfiDiceMessageContent> default_() =>
      RustLib.instance.api
          .crateApiModelFfiMessageContentDiceFfiDiceMessageContentDefault();

  Future<String> ffiToJsonString() => RustLib.instance.api
      .crateApiModelFfiMessageContentDiceFfiDiceMessageContentFfiToJsonString(
        that: this,
      );

  Future<Uint8List> ffiToProtoData({
    required String contentObj,
    FfiReferenceObj? ffiRefObj,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentDiceFfiDiceMessageContentFfiToProtoData(
        that: this,
        contentObj: contentObj,
        ffiRefObj: ffiRefObj,
      );

  Future<FfiMsgType> getFfiSubMsgType() => RustLib.instance.api
      .crateApiModelFfiMessageContentDiceFfiDiceMessageContentGetFfiSubMsgType(
        that: this,
      );

  Future<void> jsonToFfi({required String uniKey, required String jsonStr}) =>
      RustLib.instance.api
          .crateApiModelFfiMessageContentDiceFfiDiceMessageContentJsonToFfi(
            that: this,
            uniKey: uniKey,
            jsonStr: jsonStr,
          );

  Future<(String, FfiReferenceObj?)> protoDecodeToJson({
    required List<int> content,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentDiceFfiDiceMessageContentProtoDecodeToJson(
        that: this,
        content: content,
      );

  factory FfiDiceMessageContent.fromJson(Map<String, dynamic> json) =>
      _$FfiDiceMessageContentFromJson(json);
}
