// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/ffi_init_params.freezed.dart';
part '../../../../generated/src/rust/api/model/ffi_init_params.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
class FfiInitParams with _$FfiInitParams {
  const FfiInitParams._();
  const factory FfiInitParams({
    required String baseDir,
    required String secretKeyName,
    required String secretKeyValue,
    required String embedDomianHost,
    required String embedDomainOssUrl,
    required String embedLoginHost,
    required String embedLoginOssUrl,
  }) = _FfiInitParams;
  static Future<FfiInitParams> default_() =>
      RustLib.instance.api.crateApiModelFfiInitParamsFfiInitParamsDefault();

  factory FfiInitParams.fromJson(Map<String, dynamic> json) =>
      _$FfiInitParamsFromJson(json);
}
