// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/ffi_message_user.freezed.dart';
part '../../../../generated/src/rust/api/model/ffi_message_user.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
class FfiMessageUser with _$FfiMessageUser {
  const FfiMessageUser._();
  const factory FfiMessageUser({
    required PlatformInt64 senderUid,
    required String senderNickName,
    String? senderAvatar,
    required String remarkName,
  }) = _FfiMessageUser;
  static Future<FfiMessageUser> currentSender() =>
      RustLib.instance.api
          .crateApiModelFfiMessageUserFfiMessageUserCurrentSender();

  factory FfiMessageUser.fromJson(Map<String, dynamic> json) =>
      _$FfiMessageUserFromJson(json);
}
