// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadBlockData`, `DownloadCompleteInfo`, `DownloadManagerStats`, `DownloadProgressDetail`, `DownloadStatusInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 下载进度回调结果
class DownloadProgressInfo {
  /// 已下载字节数
  final PlatformInt64 downloadedBytes;

  /// 总字节数（如果已知）
  final PlatformInt64? totalBytes;

  /// 下载进度百分比 (0-100)
  final double progressPercentage;

  /// 下载URL
  final String url;

  const DownloadProgressInfo({
    required this.downloadedBytes,
    this.totalBytes,
    required this.progressPercentage,
    required this.url,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DownloadProgressInfo> newInstance({
    required PlatformInt64 downloadedBytes,
    PlatformInt64? totalBytes,
    required double progressPercentage,
    required String url,
  }) => RustLib.instance.api.crateApiModelFfiDownloadDownloadProgressInfoNew(
    downloadedBytes: downloadedBytes,
    totalBytes: totalBytes,
    progressPercentage: progressPercentage,
    url: url,
  );

  @override
  int get hashCode =>
      downloadedBytes.hashCode ^
      totalBytes.hashCode ^
      progressPercentage.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgressInfo &&
          runtimeType == other.runtimeType &&
          downloadedBytes == other.downloadedBytes &&
          totalBytes == other.totalBytes &&
          progressPercentage == other.progressPercentage &&
          url == other.url;
}
