// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'ffi_message_common.dart';
import 'ffi_message_content.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/ffi_message_content_unknown.freezed.dart';
part '../../../../generated/src/rust/api/model/ffi_message_content_unknown.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 文本消息内容
@freezed
class FfiUnknownMessageContent with _$FfiUnknownMessageContent {
  const FfiUnknownMessageContent._();
  const factory FfiUnknownMessageContent({
    required int rawMsgType,
    required String rawContent,
  }) = _FfiUnknownMessageContent;
  static Future<FfiUnknownMessageContent> default_() =>
      RustLib.instance.api
          .crateApiModelFfiMessageContentUnknownFfiUnknownMessageContentDefault();

  Future<String> ffiToJsonString() => RustLib.instance.api
      .crateApiModelFfiMessageContentUnknownFfiUnknownMessageContentFfiToJsonString(
        that: this,
      );

  Future<Uint8List> ffiToProtoData({
    required String contentObj,
    FfiReferenceObj? ffiRefObj,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentUnknownFfiUnknownMessageContentFfiToProtoData(
        that: this,
        contentObj: contentObj,
        ffiRefObj: ffiRefObj,
      );

  Future<FfiMsgType> getFfiSubMsgType() => RustLib.instance.api
      .crateApiModelFfiMessageContentUnknownFfiUnknownMessageContentGetFfiSubMsgType(
        that: this,
      );

  Future<void> jsonToFfi({
    required String uniKey,
    required String jsonStr,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentUnknownFfiUnknownMessageContentJsonToFfi(
        that: this,
        uniKey: uniKey,
        jsonStr: jsonStr,
      );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FfiUnknownMessageContent> newInstance({
    required int rawMsgType,
    required List<int> content,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentUnknownFfiUnknownMessageContentNew(
        rawMsgType: rawMsgType,
        content: content,
      );

  Future<(String, FfiReferenceObj?)> protoDecodeToJson({
    required List<int> content,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentUnknownFfiUnknownMessageContentProtoDecodeToJson(
        that: this,
        content: content,
      );

  factory FfiUnknownMessageContent.fromJson(Map<String, dynamic> json) =>
      _$FfiUnknownMessageContentFromJson(json);
}
