// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'ffi_message_common.dart';
import 'ffi_message_content.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/ffi_message_content_location.freezed.dart';
part '../../../../generated/src/rust/api/model/ffi_message_content_location.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 文本消息内容
@freezed
class FfiLocationMessageContent with _$FfiLocationMessageContent {
  const FfiLocationMessageContent._();
  const factory FfiLocationMessageContent({
    required PlatformInt64 lat,
    required PlatformInt64 lng,
    required String address,
  }) = _FfiLocationMessageContent;
  static Future<FfiLocationMessageContent> default_() =>
      RustLib.instance.api
          .crateApiModelFfiMessageContentLocationFfiLocationMessageContentDefault();

  Future<String> ffiToJsonString() => RustLib.instance.api
      .crateApiModelFfiMessageContentLocationFfiLocationMessageContentFfiToJsonString(
        that: this,
      );

  Future<Uint8List> ffiToProtoData({
    required String contentObj,
    FfiReferenceObj? ffiRefObj,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentLocationFfiLocationMessageContentFfiToProtoData(
        that: this,
        contentObj: contentObj,
        ffiRefObj: ffiRefObj,
      );

  Future<FfiMsgType> getFfiSubMsgType() => RustLib.instance.api
      .crateApiModelFfiMessageContentLocationFfiLocationMessageContentGetFfiSubMsgType(
        that: this,
      );

  Future<void> jsonToFfi({
    required String uniKey,
    required String jsonStr,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentLocationFfiLocationMessageContentJsonToFfi(
        that: this,
        uniKey: uniKey,
        jsonStr: jsonStr,
      );

  Future<(String, FfiReferenceObj?)> protoDecodeToJson({
    required List<int> content,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentLocationFfiLocationMessageContentProtoDecodeToJson(
        that: this,
        content: content,
      );

  factory FfiLocationMessageContent.fromJson(Map<String, dynamic> json) =>
      _$FfiLocationMessageContentFromJson(json);
}
