// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'ffi_message_common.dart';
import 'ffi_message_content.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/ffi_message_content_group_event.freezed.dart';
part '../../../../generated/src/rust/api/model/ffi_message_content_group_event.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 群事件消息内容
@freezed
class FfiGroupEventMessageContent with _$FfiGroupEventMessageContent {
  const FfiGroupEventMessageContent._();
  const factory FfiGroupEventMessageContent({
    required int rawMsgType,
    required String rawContent,
  }) = _FfiGroupEventMessageContent;
  static Future<FfiGroupEventMessageContent> default_() =>
      RustLib.instance.api
          .crateApiModelFfiMessageContentGroupEventFfiGroupEventMessageContentDefault();

  Future<String> ffiToJsonString() => RustLib.instance.api
      .crateApiModelFfiMessageContentGroupEventFfiGroupEventMessageContentFfiToJsonString(
        that: this,
      );

  Future<Uint8List> ffiToProtoData({
    required String contentObj,
    FfiReferenceObj? ffiRefObj,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentGroupEventFfiGroupEventMessageContentFfiToProtoData(
        that: this,
        contentObj: contentObj,
        ffiRefObj: ffiRefObj,
      );

  Future<FfiMsgType> getFfiSubMsgType() => RustLib.instance.api
      .crateApiModelFfiMessageContentGroupEventFfiGroupEventMessageContentGetFfiSubMsgType(
        that: this,
      );

  Future<void> jsonToFfi({
    required String uniKey,
    required String jsonStr,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentGroupEventFfiGroupEventMessageContentJsonToFfi(
        that: this,
        uniKey: uniKey,
        jsonStr: jsonStr,
      );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FfiGroupEventMessageContent> newInstance({
    required int rawMsgType,
    required List<int> content,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentGroupEventFfiGroupEventMessageContentNew(
        rawMsgType: rawMsgType,
        content: content,
      );

  Future<(String, FfiReferenceObj?)> protoDecodeToJson({
    required List<int> content,
  }) => RustLib.instance.api
      .crateApiModelFfiMessageContentGroupEventFfiGroupEventMessageContentProtoDecodeToJson(
        that: this,
        content: content,
      );

  factory FfiGroupEventMessageContent.fromJson(Map<String, dynamic> json) =>
      _$FfiGroupEventMessageContentFromJson(json);
}
