// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/group.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FfiGroupContactListResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// 群组基本信息的 FFI 模型
@freezed
class FfiGroupBase with _$FfiGroupBase {
  const factory FfiGroupBase({
    required PlatformInt64 groupId,
    required PlatformInt64 hostId,
    required String name,
    required String pic,
    required bool bfJoinCheck,
    required PlatformInt64 createTime,
    required PlatformInt64 memberCount,
    required bool bfJoinFriend,
    required bool bfShutup,
    required bool bfGroupReadCancel,
    required int groupMsgCancelTime,
    required bool bfBanned,
    required String groupAliasName,
  }) = _FfiGroupBase;
}

/// 群组详情的 FFI 响应模型
@freezed
class FfiGroupDetailResponse with _$FfiGroupDetailResponse {
  const factory FfiGroupDetailResponse({
    FfiGroupBase? group,
    required String groupNickName,
    required bool bfTop,
    required bool bfStar,
    required bool bfDisturb,
    required bool bfAddress,
    required int memberType,
    required bool bfMember,
    required String qrUrl,
    required PlatformInt64 qrExpire,
    required bool bfResetQrcode,
  }) = _FfiGroupDetailResponse;
}
