// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part '../../../../generated/src/rust/api/model/user.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 用户个人信息视图模型
@freezed
class FfiUser with _$FfiUser {
  const factory FfiUser({
    required PlatformInt64 uid,
    String? nickName,
    String? icon,
    int? privacy,
    int? gender,
    String? signature,
    int? viewType,
    int? language,
    int? clearTime,
    String? identify,
    String? phone,
    String? email,
  }) = _FfiUser;
}

/// User information essential for initial UI display after login.
@freezed
class FfiUserBase with _$FfiUserBase {
  const factory FfiUserBase({
    required PlatformInt64 uid,
    required String nickName,
    required String avatar,
  }) = _FfiUserBase;
}
