// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model/ffi_channel_model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取频道详情
///
/// 参数：
/// * `channel_id` - 频道ID
Future<FfiChannelModel?> getChannelDetail({required PlatformInt64 channelId}) =>
    RustLib.instance.api.crateApiChannelApiGetChannelDetail(
      channelId: channelId,
    );

/// 获取通讯录中的频道列表
Future<List<FfiChannelModel>> getChannelContactList() =>
    RustLib.instance.api.crateApiChannelApiGetChannelContactList();

Future<int> getChannelMemberCount({required String conversationId}) => RustLib
    .instance
    .api
    .crateApiChannelApiGetChannelMemberCount(conversationId: conversationId);
