// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model/ffi_message_common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> getConversationId({
  required FfiChatType chatType,
  required PlatformInt64 targetId,
}) => RustLib.instance.api.crateApiConversationIdUtilGetConversationId(
  chatType: chatType,
  targetId: targetId,
);

Future<String> genarateConversationId({
  required int chatTypeVal,
  required PlatformInt64 targetId,
}) => RustLib.instance.api.crateApiConversationIdUtilGenarateConversationId(
  chatTypeVal: chatTypeVal,
  targetId: targetId,
);

Future<PlatformInt64> getTargetIdFromConversationId({
  required String conversationId,
}) => RustLib.instance.api
    .crateApiConversationIdUtilGetTargetIdFromConversationId(
      conversationId: conversationId,
    );

Future<(FfiChatType, PlatformInt64)> parseConversationId({
  required String conversationId,
}) => RustLib.instance.api.crateApiConversationIdUtilParseConversationId(
  conversationId: conversationId,
);
