// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model/group.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取群组详情
///
/// 参数：
/// * `group_id` - 群组ID
Future<FfiGroupDetailResponse> getGroupDetail({
  required PlatformInt64 groupId,
}) => RustLib.instance.api.crateApiGroupApiGetGroupDetail(groupId: groupId);

/// 获取通讯录中的群组列表
Future<List<FfiGroupBase>> getGroupContactList() =>
    RustLib.instance.api.crateApiGroupApiGetGroupContactList();

Future<int> getGroupMemberCount({required String conversationId}) => RustLib
    .instance
    .api
    .crateApiGroupApiGetGroupMemberCount(conversationId: conversationId);
