// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model/user.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ffi_user_to_user_model`, `user_model_to_ffi_user`

/// 获取用户个人信息
/// 优先从本地数据库获取，如果不存在则从服务器获取并保存到数据库
Future<FfiUser> getUser({required PlatformInt64 uid}) =>
    RustLib.instance.api.crateApiUserApiGetUser(uid: uid);

/// 从服务器刷新用户个人信息
Future<FfiUser> refreshUser({required PlatformInt64 uid}) =>
    RustLib.instance.api.crateApiUserApiRefreshUser(uid: uid);

/// 更新用户个人信息
Future<void> updateUser({required FfiUser ffiUser}) =>
    RustLib.instance.api.crateApiUserApiUpdateUser(ffiUser: ffiUser);

/// 监听用户信息更新
///
/// 返回:
/// * `Stream<String>` - 用户信息更新事件流
Stream<FfiUser> listenForUserInfoUpdates() =>
    RustLib.instance.api.crateApiUserApiListenForUserInfoUpdates();
